image: alpine/edge
packages:
  - go
  - make
sources:
  - https://git.sr.ht/~bacardi55/walgot
tasks:
  - setup: |
      cd walgot
      make dependencies
  - test: |
      cd walgot
      go test ./...
  - build: |
      cd walgot
      make buildAll
artifacts:
  - walgot/bin/walgot_linux_amd64
  - walgot/bin/walgot_linux_arm
  - walgot/bin/walgot_linux_arm64
  - walgot/bin/walgot_linux_386
triggers:
  - action: email
    condition: always
    to: bac@rdi55.pl
